import { NextRequest, NextResponse } from 'next/server';
import { pool } from '@/lib/db';

// In-memory presence map. Module-scope state persists across requests
// within a single server instance, which is fine for the live-subjects
// panel — it's a best-effort presence indicator with a 30s TTL.
//
// Cold-start (Vercel) wipes the Map; players will repopulate on their
// next heartbeat (every 10s).
type Entry = { name: string; lastSeen: number };
const players: Map<string, Entry> = (globalThis as { __finalGamePlayers?: Map<string, Entry> }).__finalGamePlayers ?? new Map();
(globalThis as { __finalGamePlayers?: Map<string, Entry> }).__finalGamePlayers = players;

const TTL_MS = 30_000;

function cleanup() {
  const now = Date.now();
  for (const [id, p] of players) {
    if (now - p.lastSeen > TTL_MS) players.delete(id);
  }
}

interface SessionRow {
  user_id: string;
  user_name: string;
}

async function getSessionName(req: NextRequest): Promise<SessionRow | null> {
  const sessionId = req.cookies.get('atlas_sid')?.value;
  if (!sessionId) return null;
  try {
    const res = await pool.query<SessionRow>(
      `SELECT user_id, user_name FROM sessions WHERE id = $1 AND expires_at > NOW()`,
      [sessionId]
    );
    return res.rows[0] ?? null;
  } catch {
    return null;
  }
}

const noCache = { 'Cache-Control': 'no-store' };

export async function GET() {
  cleanup();
  // Return up to 50 names — the panel only shows a handful anyway.
  const list = Array.from(players.values())
    .sort((a, b) => b.lastSeen - a.lastSeen)
    .slice(0, 50)
    .map((p) => ({ name: p.name }));
  return NextResponse.json({ players: list }, { headers: noCache });
}

// Heartbeat. Body: { clientId: string, name: string }.
// clientId is generated by the iframe (sessionStorage UUID) so multiple
// tabs/devices for the same team count as separate live subjects.
export async function POST(req: NextRequest) {
  cleanup();
  const body = await req.json().catch(() => null);
  if (!body || typeof body !== 'object') {
    return NextResponse.json({ error: 'Invalid body' }, { status: 400, headers: noCache });
  }
  const session = await getSessionName(req);
  const rawName = (body.name ?? session?.user_name ?? 'Anonymous').toString();
  const name = rawName.trim().slice(0, 32) || 'Anonymous';
  const clientId = (body.clientId ?? '').toString().trim().slice(0, 64);
  if (!clientId) {
    return NextResponse.json({ error: 'clientId required' }, { status: 400, headers: noCache });
  }
  players.set(clientId, { name, lastSeen: Date.now() });
  return NextResponse.json({ ok: true, count: players.size }, { headers: noCache });
}

// Explicit removal — fired when the player wins/loses or unloads the page.
export async function DELETE(req: NextRequest) {
  const url = new URL(req.url);
  const clientId = (url.searchParams.get('clientId') ?? '').trim().slice(0, 64);
  if (clientId) players.delete(clientId);
  return NextResponse.json({ ok: true }, { headers: noCache });
}
